
namespace MirRemake {
    enum NetworkToClientDataType : byte {
        INIT_SELF_NETWORK_ID,
        INIT_SELF_INFO,
        APPLY_OTHER_ACTOR_UNIT_IN_SIGHT,
        SET_OTHER_POSITION,
        SET_ALL_HP_AND_MP,
        APPLY_OTHER_CAST_SKILL_BEGIN,
        APPLY_OTHER_CAST_SKILL_SING_CANCEL,
        APPLY_ALL_EFFECT,
        APPLY_ALL_DEAD,
        APPLY_SELF_USE_CONSUMABLE_ITEM,
        APPLY_SELF_USE_EQUIPMENT_ITEM,
        APPLY_OTHER_USE_EQUIPMENT_ITEM,
        APPLY_SELF_ACCECPT_MISSION,
        APPLY_SELF_DELIVER_MISSION,
        APPLY_SELF_CANCEL_MISSION,
        APPLY_SELF_TALK_TO_MISSION_NPC,
        APPLY_SELF_UPDATE_SKILL_LEVEL_AND_MASTERLY_AND_MONEYCOST
    }
    enum NetworkToServerDataType : byte {
        INIT_PLAYER_ID,
        SET_POSITION,
        APPLY_CAST_SKILL_BEGIN,
        APPLY_CAST_SKILL_SETTLE,
        APPLY_CAST_SKILL_SING_CANCEL,
        APPLY_PICK_UP_ITEM_ON_GROUND,
        APPLY_DROP_ITEM_ONTO_GROUND,
        APPLY_USE_CONSUMABLE_ITEM,
        APPLY_USE_EQUIPMENT_ITEM,
        APPLY_ACCEPT_MISSION,
        APPLY_DELIVER_MISSION,
        APPLY_CANCEL_MISSION,
        APPLY_TALK_TO_MISSION_NPC,
        APPLY_UPDATE_SKILL_LEVEL
    }
}